### ISSUE TITLE
Editor broken, after add icon in project

### ISSUE THREAD

**Issue by cesarjrccorreia** [interisti/vs-material-icons-generator#19] opened 2018-04-02 15:04 UTC
### Installed product versions
- Visual Studio: VS Community 2017, Version: 15.5.7
- This extension: 1.5.3

### Description
After add icon in project, the editor of visual studio broken and I can't edit files. The editor back to normal after restart visual studio.

### Steps to recreate
1. Open material extension
2. Choose one icon
3. Add in project
4. Close material extension

### Current behavior
I can't edit files after add icons in project.

![error](https://user-images.githubusercontent.com/6727025/38201441-ac369ad0-366e-11e8-9101-fc167b9de1c4.PNG)

### Expected behavior
Can edit files after add icons in project.

**Comment by jstun** [comment] 2018-04-29 13:43
I'm having the same issue. I have to close VS 2017 15.6.7 and reopen.

**Comment by interisti** [comment] 2018-05-05 14:27
Thanks for reporting, though i have same versions and i can't reproduce that bug. Can you share the VS logs?

**Comment by vinicius-stutz** [comment] 2018-05-17 19:55
I'm having the same issue. I have to close VS 2017 (v 15.7.1) and reopen. I can't use 'Backspace', 'Arrows' and 'Return' keys in code editor. When I try to close the IDE, the message pops up:

---------------------------
Microsoft Visual Studio

Microsoft Visual Studio has detected that an operation is blocking user input.  This can be caused by an active modal dialog or a task that needs to block user interaction.  Would you like to shut down anyway?

Yes   No   

---------------------------

**Comment by interisti** [comment] 2018-05-18 07:40
@vinicius-stutz 

i think ill prepare a debug version of the extension, can you install that and share logs ?

**Comment by vinicius-stutz** [comment] 2018-05-18 14:53
Yes, it would be an honor!

​Att,
Vinícius

**Comment by interisti** [comment] 2018-05-18 17:00
Hi @vinicius-stutz 
Thanks for help, here is the debug version of the extension 
https://drive.google.com/file/d/1lHb35X0iPDN3Zq3X4B8lZA0ccEB1b5hU/view?usp=sharing

it will create a `material-icons-generator.log` file in `My Documents` dir with debug messages.

**Comment by vinicius-stutz** [comment] 2018-05-18 18:47
Hello buddy! The LOG:

Updating preview image: ic_close
Updating preview image: ic_close
Got preview image data: 148
Finish preview image: ic_close
Got preview image data: 148
Finish preview image: ic_close
Updating preview image: ic_close
Got preview image data: 149
Finish preview image: ic_close
Updating preview image: ic_close
Got preview image data: 257
Finish preview image: ic_close
Start Downloading package: ic_close - white - 48dp
Start Downloading density: mdpi
End Downloading density: mdpi
Start Downloading density: hdpi
End Downloading density: hdpi
Start Downloading density: xhdpi
End Downloading density: xhdpi
Start Downloading density: xxhdpi
End Downloading density: xxhdpi
Start Downloading density: xxxhdpi
End Downloading density: xxxhdpi
Start Downloading density: drawable
End Downloading density: drawable
Finish Downloading package: ic_close

Unfortunately VS2017 continues to crash at the end of the process and,
closing the IDE, I keep getting the message:
​ ​
"Microsoft Visual Studio has detected that an operation is blocking user
input. This can be caused by an active modal dialog or a task that needs to
block user interaction. Would you like to shut down anyway?"

Att,
Vinícius

>

**Comment by interisti** [comment] 2018-05-18 19:39
@vinicius-stutz 
One more test please

https://drive.google.com/file/d/1MFkfE3lGBvPYLWe6BuY04iQYSEfa8fxN/view?usp=sharing

**Comment by vinicius-stutz** [comment] 2018-05-18 19:49
Again...

Updating preview image: ic_close
Updating preview image: ic_close
Got preview image data: 148
Finish preview image: ic_close
Got preview image data: 148
Finish preview image: ic_close
Updating preview image: ic_close
Got preview image data: 149
Finish preview image: ic_close
Updating preview image: ic_close
Got preview image data: 257
Finish preview image: ic_close
Start Downloading package: ic_close - white - 48dp
Start Downloading density: mdpi
End Downloading density: mdpi
Start Downloading density: hdpi
End Downloading density: hdpi
Start Downloading density: xhdpi
End Downloading density: xhdpi
Start Downloading density: xxhdpi
End Downloading density: xxhdpi
Start Downloading density: xxxhdpi
End Downloading density: xxxhdpi
Start Downloading density: drawable
End Downloading density: drawable
Finish Downloading package: ic_close
Updating preview image: ic_account_circle
Updating preview image: ic_account_circle
Got preview image data: 266
Finish preview image: ic_account_circle
Finish preview image: ic_account_circle
Got preview image data: 266
Updating preview image: ic_account_circle
Got preview image data: 270
Finish preview image: ic_account_circle
Updating preview image: ic_account_circle
Got preview image data: 632
Finish preview image: ic_account_circle
Start Downloading package: ic_account_circle - white - 48dp
Start Downloading density: mdpi
End Downloading density: mdpi
Start Downloading density: hdpi
End Downloading density: hdpi
Start Downloading density: xhdpi
End Downloading density: xhdpi
Start Downloading density: xxhdpi
End Downloading density: xxhdpi
Start Downloading density: xxxhdpi
End Downloading density: xxxhdpi
Start Downloading density: drawable
End Downloading density: drawable
Finish Downloading package: ic_account_circle

And the same problem happened​, sorry.

Att,
Vinícius

**Comment by interisti** [comment] 2018-05-18 19:53
@vinicius-stutz 
hmm seems its an `StatusBar.Clear` issue, since logs do not contain debug message: `"Cleared Status Bar"`
Can you try this https://drive.google.com/file/d/1iTdWKTJnNxbbu4WXMTHheMQxUvcRFrNv/view?usp=sharing one more time to verify that, please.

**Comment by vinicius-stutz** [comment] 2018-05-21 20:49
@interisti, it's ok now!

See the log:

Updating preview image: ic_close
Updating preview image: ic_close
Got preview image data: 148
Finish preview image: ic_close
Got preview image data: 148
Finish preview image: ic_close
Updating preview image: ic_close
Got preview image data: 149
Finish preview image: ic_close
Updating preview image: ic_close
Got preview image data: 257
Finish preview image: ic_close
Start Downloading package: ic_close - white - 48dp
Start Downloading density: mdpi
End Downloading density: mdpi
Start Downloading density: hdpi
End Downloading density: hdpi
Start Downloading density: xhdpi
End Downloading density: xhdpi
Start Downloading density: xxhdpi
End Downloading density: xxhdpi
Start Downloading density: xxxhdpi
End Downloading density: xxxhdpi
Start Downloading density: drawable
End Downloading density: drawable
Finish Downloading package: ic_close
Updating preview image: ic_account_circle
Updating preview image: ic_account_circle
Got preview image data: 266
Finish preview image: ic_account_circle
Finish preview image: ic_account_circle
Got preview image data: 266
Updating preview image: ic_account_circle
Got preview image data: 270
Finish preview image: ic_account_circle
Updating preview image: ic_account_circle
Got preview image data: 632
Finish preview image: ic_account_circle
Start Downloading package: ic_account_circle - white - 48dp
Start Downloading density: mdpi
End Downloading density: mdpi
Start Downloading density: hdpi
End Downloading density: hdpi
Start Downloading density: xhdpi
End Downloading density: xhdpi
Start Downloading density: xxhdpi
End Downloading density: xxhdpi
Start Downloading density: xxxhdpi
End Downloading density: xxxhdpi
Start Downloading density: drawable
End Downloading density: drawable
Finish Downloading package: ic_account_circle
Updating preview image: ic_arrow_back
Updating preview image: ic_arrow_back
Got preview image data: 104
Finish preview image: ic_arrow_back
Finish preview image: ic_arrow_back
Got preview image data: 104
Updating preview image: ic_arrow_back
Got preview image data: 106
Finish preview image: ic_arrow_back
Updating preview image: ic_arrow_back
Got preview image data: 131
Finish preview image: ic_arrow_back
Start Downloading package: ic_arrow_back - white - 48dp
Start Downloading density: mdpi
End Downloading density: mdpi
Start Downloading density: hdpi
End Downloading density: hdpi
Start Downloading density: xhdpi
End Downloading density: xhdpi
Start Downloading density: xxhdpi
End Downloading density: xxhdpi
Start Downloading density: xxxhdpi
End Downloading density: xxxhdpi
Start Downloading density: drawable
End Downloading density: drawable
Finish Downloading package: ic_arrow_back
Cleared Status Bar

Nice work, thank you!

**Comment by interisti** [comment] 2018-05-21 20:59
@vinicius-stutz 
great, i'll release fixed version.
Thanks for your help.

cheers.

**Comment by interisti** [comment] 2018-05-22 22:46
@vinicius-stutz  @cesarjrccorreia  @jstun

I've uploaded a new version of the extension, can you guys update it and check if it works, then close the issue.

Regards.

**Comment by cesarjrccorreia** [comment] 2018-05-23 12:11
Hi @interisti 
When I use version MaterialIconsGenerator-TROUBLESHOOT-3 works fine. But when I use version 1.6.0 the error persists.

Thanks for your help.

**Comment by interisti** [comment] 2018-05-23 12:32
Hi @cesarjrccorreia 
Thanks for testing, Can i ask you to test this version please 
https://drive.google.com/open?id=1RNFO5T0pZgnV7jONgapc44r0_uw2Sl04

**Comment by cesarjrccorreia** [comment] 2018-05-23 13:12
Hi, not work (version 1.6.1), same error occurs.
![error](https://user-images.githubusercontent.com/6727025/40426519-aecae3e8-5e71-11e8-8eb3-5d85ca48409b.PNG)

**Comment by interisti** [comment] 2018-05-23 13:18
ok, Thanks.

i'll remove the status bar message and icon entirely.

**Comment by interisti** [comment] 2018-05-23 18:40
@cesarjrccorreia  just published 1.6.1, i hope it works this time.

**Comment by cesarjrccorreia** [comment] 2018-05-23 18:53
@interisti Nice works fine now.

Thanks for your help.

**Closed as completed** 2018-05-23 18:56 UTC

**Comment by jstun** [comment] 2018-05-25 15:51
@interisti I tested this item and it's working for me as well.

This is a huge time saver. Thanks for the great work on this.
